### ISSUE TITLE
P6 Cocounts arrays are not available

### ISSUE THREAD

**Issue by evromero-uw** [iosonofabio/hivwholeweb#2]
Hello,
I am trying to download the arrays of pairs of SNPs for each individual. Whenever I click one of the links to download the p6 cocounts I get a 404 Not Found message. For example, the URL I am trying to access is 

https://hiv.biozentrum.unibas.ch/download/cocounts_p6_1_F1.zip

The download seems to be working for other individuals though. 

Thank you for your help
Elena Romero

**Comment by iosonofabio** [comment]
Hi Elena,

Thanks for writing. I'm not involved in this project since ~2016. Please open the same issue on https://github.com/neherlab/hivwholeweb.

Pinging @rneher who's the head of that lab and might fix it/ask someone to fix it after you open the issue over there.

Closing
